#!/bin/sh
# put to /usr/local/bin/

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# Fix Firefox is already running 
export MOZ_DBUS_REMOTE=1

# Vulkan
# export WLR_RENDERER=vulkan

exec dbus-launch sway &>~/log/sway.log$@

#
# If you use systemd and want sway output to go to the journal, use this
# instead of the `exec sway $@` above:
#
#    exec systemd-cat --identifier=sway sway $@
#
